### ISSUE TITLE
[wppb-login]'s user activation not working in template php file.

### ISSUE THREAD

**Issue by bissy** [foliovision/profile-builder#2]
Hi,
When I write [wppb-login] in template file, new user's activation was not working.
like below,
<?php echo do_shortcode('[wppb-login]'); ?>

How should I do?

**Comment by foliovision** [comment]
Hello bissy,

I'm sorry, but this repository is not the official Profile Builder one. We only created it to created it to submit some bugfixes to the original plugin creator whom you can contact here: https://www.cozmoslabs.com/support/

Thanks,
Martin

**Comment by bissy** [comment]
Hi Martin!
Ooops, I'm sorry and thank you information.
